### ISSUE TITLE
Database Migrations

### ISSUE THREAD

**Issue by cpressland** [binkhq/api-reflector#13]
Unable to perform database migration as `alembic` is not installed on the container image:

```
$ alembic head upgrade
bash: alembic: command not found
```

We should consider including alembic in the projects main dependencies instead of exclusively in the dev dependencies group. After manually installing `alembic` via `pip install alembic` we recieve the following error:

```
$ alembic upgrade head
FAILED: No config file 'alembic.ini' found, or file has no '[alembic]' section
```

We can either include any required migrations and the alembic.ini file in the python wheel or `COPY` them directly into the container from the previous build phase.

**Comment by backwardspy** [comment]
i agree we need a solution for this.
for now, i am running the local migrations against the remote database, but it would be nice to have the app run these automatically on startup. alembic can be invoked programmatically, so we can write a startup procedure to do this.
