### ISSUE TITLE
catch template errors and return an informative message in the response body

### ISSUE THREAD

**Issue by backwardspy** [binkhq/api-reflector#48]

**Comment by haffi96** [comment]
Does the 'catch template errors' in the title refer to a request not being a `templateable_request`? https://github.com/binkhq/api-reflector/blob/07f89b387cf3700eabf7b7f06ccb21d36d8c76da/api_reflector/views.py#L108

**Comment by backwardspy** [comment]
this issue could certainly use some more detail! :)

it's mostly referring to this line here:
https://github.com/binkhq/api-reflector/blob/07f89b387cf3700eabf7b7f06ccb21d36d8c76da/api_reflector/rules_engine.py#L101
when we call `.render(...)` on the rule template, and here:
https://github.com/binkhq/api-reflector/blob/07f89b387cf3700eabf7b7f06ccb21d36d8c76da/api_reflector/views.py#L113-L118
when we call `.render(...)` on the response template.

these template renders can fail, and at the moment if that happens you just get back a generic error. it would be nice to catch those errors and return some useful information about what went wrong and where.

**Comment by backwardspy** [comment]
sounds good, thank you!

in the end, any error handling is better than none. returning detailed information about what exactly went wrong would be great, but even just returning a generic 400 error saying "error rendering template" is much better than it crashing as it does right now!
