### ISSUE TITLE
key-value storage for rules and templating

### ISSUE THREAD

**Issue by backwardspy** [binkhq/api-reflector#53]
we could expose a `storage` object on [TemplatableRequest](https://github.com/binkhq/api-reflector/blob/6bfd8015cee581a7a644f9413aef8b3029e0b807/api_reflector/rules_engine.py#L63-L71) that allows users to temporarily store a key-value pair in an action, and read a key-value pair in a template. all stored key-value pairs would be given a short (configurable) expiry to help prevent leaving mock endpoints in an unknown state.

this feature would allow us to simulate more complex logic in responses. for example, you could simulate an auth flow like this:

**GET /users/me**
* 401 Unauthorized
* 200 OK
  * rule: {{ request.storage.authorized }} EQUAL true

**POST /auth**
* 200 OK
  * action: STORE authorized true

with these endpoints & responses set up, the following flow would be possible:
1. `GET /users/me` responds `401 Unauthorized`.
2. `POST /auth` responds `200 OK` and in the kv-store `authorized` is set to `true`.
3. `GET/users/me` now responds `200 OK` thanks to the passing rule improving that response's score.
4. wait a minute for the key to expire
5. `GET /users/me` now responds `401 Unauthorized` again.

**Comment by backwardspy** [comment]
the storage backend should ideally be something lightweight that makes local development and testing easy. we could also consider making the backend configurable so users can swap out for something more suited for deployment in a distributed system such as redis.

consider technologies such as [leveldb](https://plyvel.readthedocs.io/en/latest/), [lmdb](https://lmdb.readthedocs.io/en/release/), and [rocksdb](https://python-rocksdb.readthedocs.io/en/latest/).

**Comment by haffi96** [comment]
I was looking at ways to implement this yesterday. Is this still a wanted feature?

**Comment by backwardspy** [comment]
> I was looking at ways to implement this yesterday. Is this still a wanted feature?

absolutely, it's nothing we need ourselves right now but i think it could be useful functionality for a variety of use cases. i'd be happy to review a PR for it.

**Comment by haffi96** [comment]
I have a few questions, sorry alot of questions 😭 :
> POST /auth
>
>    200 OK
>    action: STORE authorized true

1. So we specifically want the process of adding a k-v to the storage via a configured action? Instead of directly just directly adding to storage when a POST /auth is hit

2. if the data being stored in the storage looks like this, we could have auth for each endpoint. Did you have a different structure in mind?

```json
{"/some_id/enrolment": "{'auth': True, 'expiry': 1666270493.341728}"}
```
 
> all stored key-value pairs would be given a short (configurable) expiry

3. Configurable via env variable or argument on the action? 

4. I've had some trouble building Leveldb and Rocksdb locally (on Intel Mac). Well I can install them via brew just fine. But the python client library for them both fails to compile/import modules, think I need to link gcc to the lib or something, but Im not familiar with this. Idk if this made sense

For the time being, Im using https://pythonhosted.org/pickleDB/ this to test. But can change this out for any preferred/better one as long as I can build it locally.

**Comment by backwardspy** [comment]
> I have a few questions, sorry alot of questions sob :
> 
> > POST /auth
> > 200 OK
> > action: STORE authorized true
> 
>     1. So we specifically want the process of adding a k-v to the storage via a configured action? Instead of just directly adding to storage when a POST /auth is hit

yeah, the auth thing is just an example of how this storage system could be applied. the idea is for it to be as generic as possible, and actions + rules seem to be the perfect match for this.

>     2. if the data being stored in the storage looks like this, we could have auth for each endpoint. Did you have a different structure in mind?
> 
> 
> ```json
> k-v from storage
> {"endpoint_path": "{}"}
> i.e
> {"/some_id/enrolment": "{'auth': True, 'expiry': 1666270493.341728}"}
> ```

some kv storage systems (redis comes to mind) have built-in expiry support. if the tech we end up going with doesn't have native key expiry then something like this will work fine.

> Original endpoint which gets 401 without auth: `/mock/<some_id>/enrolment` The auth call for this endpoint: POST `/mock/<some_id>/enrolment/auth` which will add the path as the key, and set auth value to true
> 
> > all stored key-value pairs would be given a short (configurable) expiry
> 
>     3. Configurable via env variable or argument on the action? This may also automatically answer question 1

env var should be fine for mvp :)

>     4. I've had some trouble building Leveldb and Rocksdb locally (on Intel Mac). Well I can install them via brew just fine. But the python client library for them both fails to compile/import modules, think I need to link gcc to the lib or something, but Im not familiar with this. Idk if this made sense. Do you happen to have a process to build these?
> 
> 
> For the time being, Im using https://pythonhosted.org/pickleDB/ this to test. But can change this out for any preferred/better one as long as I can build it locally.

i used one of them, i forget which, a while ago. i don't remember the details of setting it up i'm afraid. i'm not too precious about the tech choice to be honest, as long as it makes local dev & testing easy and it's actively maintained.

on that point, it would be great if we could abstract the storage interface away from the storage backend at all. this would facilitate adding support for other technologies in future. for this first draft though i'm perfectly happy leaving that out and just tying it to one specific mechanism.
