### ISSUE TITLE
slow type checking

### ISSUE THREAD

**Issue by backwardspy** [binkhq/api-reflector#69]
mypy is taking a while on this repo, possibly due to complex sqlalchemy types(?)
there may be nothing we can do about this, but it's worth looking into for faster pipelines.

**Comment by haffi96** [comment]
It was noticeably slower for the CI build for [(3.11, 1.4, macos-latest)](https://github.com/binkhq/api-reflector/actions/runs/5289244002/jobs/9571940591#logs)

mypy version is currently at 0.981, thought it might be worth attempting to update it to the latest first (1.4.1). Unless there was a specific reason to not update?

Have opened this https://github.com/binkhq/api-reflector/pull/71 to test, CI builds seem quicker

**Comment by backwardspy** [comment]
the builds are indeed much quicker, so i'll call this fixed for now. thanks!
